# Generated by Django 3.0.5 on 2020-06-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likeField',
            field=models.CharField(max_length=255),
        ),
    ]
