# Generated by Django 3.0.5 on 2020-06-09 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200609_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 17, 6, 27, 816126, tzinfo=utc)),
        ),
    ]
