# Generated by Django 3.0.5 on 2020-06-10 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200611_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 23, 23, 23, 184573, tzinfo=utc)),
        ),
    ]
